---
- name: Install CloudWatch Agent
  hosts: 127.0.0.1
  become: yes  # Use sudo privileges

  tasks:
    - name: Download CloudWatch Agent installer
      get_url:
        url: https://s3.amazonaws.com/amazoncloudwatch-agent/ubuntu/amd64/latest/amazon-cloudwatch-agent.deb
        dest: ./amazon-cloudwatch-agent.deb
        mode: '0644'

    - name: Install CloudWatch Agent
      shell: sudo dpkg -i -E ./amazon-cloudwatch-agent.deb

    - name: Moving config
      shell: sudo mv /home/siemens/ansible_repo/cloudwatch/cloudwatch_config.json /opt/aws/amazon-cloudwatch-agent/bin

    - name: Starting cwagent
      shell: sudo /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl -a fetch-config -m ec2 -s -c file:/opt/aws/amazon-cloudwatch-agent/bin/cloudwatch_config.json
