---
- name: Configure Nginx Web Server
  hosts: 127.0.0.1
  become: true

  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present
      tags:
        - nginx

    - name: Enable Nginx service
      systemd:
        name: nginx
        enabled: yes
        state: started
      tags:
        - nginx

    - name: Copy Nginx configuration file
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/nginx.conf
      notify: Reload Nginx
      tags:
        - nginx

  handlers:
    - name: Reload Nginx
      systemd:
        name: nginx
        state: reloaded
